version: '3.7'

services:
  web:
    build: .
    container_name: trading_django
    command: 
      bash -c "python manage.py makemigrations 
      && python manage.py migrate 
      && python manage.py collectstatic --noinput
      && gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers=2 --timeout 800"
    volumes:
      - ./app:/app/
      - staticfiles:/app/static/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: trading_postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PSWD}
    ports: 
      - ${DB_EXTERNAL_PORT}:5432

  nginx:
    build: ./nginx
    container_name: trading_ngx
    volumes:
      - staticfiles:/app/static/
    ports:
      - ${NGINX_EXTERNAL_PORT}:80
    depends_on:
      - web

volumes:
  postgres_data:
  staticfiles:
